### ISSUE TITLE
Getting to work on windows

### ISSUE THREAD

**Issue by JacYuan1** [ShotokanZH/flipper_sub_plotters_comparers#3]
Hi,

I am using your tool to parse a flipper zero signal I caught however, I noticed your commands are being ran on Linux operating systems but in my case I'm using Windows OS. Is there a way to convert this line: "python3 -BO plotall.py sample_files/433_Tesla_* --outfile out/out_plotall.html" to windows PowerShell? I have attached a screenshot as to what I mean. I'm also using VS Code.

![image](https://user-images.githubusercontent.com/121719446/222434358-b128f1bb-cf0a-41a7-bc54-56766f038112.png)

Thanks

**Comment by ShotokanZH** [comment]
You can try and just write the slashes in the opposite direction:
\ instead of /
